services:
  postgres:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - ./app.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  scrape:
    container_name: scrape
    depends_on:
      - postgres
    build:
      context: ./scrape
      dockerfile: Dockerfile
    env_file:
      - ./app.env
volumes:
  db:
