apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scrape
  description: The scraper for the Tanzu Trends Demo Application
  tags:
    - golang
  links:
    - url: github.com/n0madic/twitter-scraper
      title: Twitter Scraper Github Page
      icon: dashboard
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=tanzutrends
spec:
  type: service
  lifecycle: production
  owner: denmark-team
  system: tanzutrends
  dependsOn:
    - resource:default/tanzutrends-db
