apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: tanzutrends-db
  namespace: default
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: tanzutrends-db-db-secret
    namespace: default
