apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app.kubernetes.io/name: tanzutrends-db-0
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
