apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: scrape
  labels:
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/part-of: tanzutrends
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  serviceClaims:
    - name: tanzutrends-db
      ref:
        apiVersion: v1
        kind: Secret
        name: tanzutrends-db-db-secret
  source:
    git:
      url: https://github.com/TanzuDK/TanzuTrends.git
      ref:
        branch: main
    subPath: scrape
